### ISSUE TITLE
Dataset Candidates

### ISSUE THREAD

**Issue by kcamcam** [kcamcam/Big-Data#1]
Both datasets from the Montreal Open Information Portal look interesting:
- [Road Collisions](http://donnees.ville.montreal.qc.ca/dataset/collisions-routieres)
- [Metro Incidents Reports](http://donnees.ville.montreal.qc.ca/dataset/incidents-du-reseau-du-metro)

**Comment by kkhh001** [comment]
**Lab Notes**

- Generate some negatives to complement our data set
- Add features: Weather, Holidays, etc
- 2 Algorithms: Classifications & .... (ie Clustering, etc) refer to first lecture slide
